### ISSUE TITLE
Sequence diagramm: Move

### ISSUE THREAD

**Issue by Barnald** [4BITbme/4bit-issuelog#4]

**Comment by barlord** [comment]
current - + megcserélése
visszatérés nyilak pótlás+csere szaggatottra

**Comment by barlord** [comment]
![Image](https://user-images.githubusercontent.com/64486378/226097012-e2bed5d0-7d0e-4604-92b7-cdce27f8a24b.png)

**Comment by barlord** [comment]
![Image](https://user-images.githubusercontent.com/64486378/226097344-eecf3863-3efd-4f6c-a789-793318fa780f.png)
